SuggestionsView = require './suggestions.coffee'

# template            = -> require('../../templates/galleries.jade') arguments...
# suggestedTemplate   = -> require('../../templates/suggested_galleries.jade') arguments...

module.exports = class GalleriesView extends SuggestionsView
  template:     -> require('../../templates/galleries.jade') arguments...
  key:          'personalize:suggested-galleries'
  restrictType: 'PartnerGallery'
