language: node_js
node_js:
  - '6'
before_install:
  - rvm install 2.3.1
script:
  - "rvm use 2.3.1 && gem install danger  --version '~> 4.0' && danger"
  - npm test
env:
  secure: Eeh6erKjEBwpuADXXPJJlaQgO+qLBa8pBkqgI/Y3uH5y/qlT7nkFkzwCzbKLLjgrWmuAHlseo9ulj09n7BmC55RyXXHczhQi3SiAeXuK2x0s/qLsePtu5F5zgFlj+mDR6mYOeZaCWJN4OA8D0RNN40YCOUh/ubivEsnxc58Nw+w=
