nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.11.0.cjs

# Disable postinstall scripts from 3rd parties. In 2025, libraries really
# shouldn't need this, and if they do we should evaulate them one-by-one.
enableScripts: false
