export const collectionToArtistSeriesSlugMap = {
  "alex-katz-departure": "alex-katz-departure",
  "alex-katz-pas-de-deux": "alex-katz-pas-de-deux",
  "alex-katz-ada": "alex-katz-ada",
  "alex-katz-black-dress": "alex-katz-black-dress",
  "alex-katz-chance": "alex-katz-chance",
  "alex-katz-coca-cola-girls": "alex-katz-coca-cola-girls",
  "banksy-barcode": "banksy-barcode",
  "banksy-choose-your-weapon": "banksy-choose-your-weapon",
  "banksy-donuts": "banksy-donuts",
  "banksy-flying-copper": "banksy-flying-copper",
  "banksy-forgive-us-our-trespassing": "banksy-forgive-us-our-trespassing",
  "banksy-golf-sale": "banksy-golf-sale",
  "banksy-grannies": "banksy-grannies",
  "banksy-happy-choppers": "banksy-happy-choppers",
  "banksy-hmv": "banksy-hmv",
  "banksy-i-fought-the-law": "banksy-i-fought-the-law",
  "banksy-jack-and-jill": "banksy-jack-and-jill",
  "banksy-morons": "banksy-morons",
  "banksy-no-ball-games": "banksy-no-ball-games",
  "banksy-pulp-fiction": "banksy-pulp-fiction",
  "banksy-queen-victoria": "banksy-queen-victoria",
  "banksy-rain": "banksy-rain",
  "banksy-sale-ends-today": "banksy-sale-ends-today",
  "banksy-stop-and-search": "banksy-stop-and-search",
  "banksy-trolleys": "banksy-trolleys",
  "banksy-bomb-hugger": "banksy-bomb-hugger",
  "banksy-flower-throwers": "banksy-flower-throwers",
  "banksy-kate-moss": "banksy-kate-moss",
  "banksy-monkeys": "banksy-monkeys",
  "banksy-rats": "banksy-rats",
  "banksy-soup-cans": "banksy-soup-cans",
  "banksy-di-faced-tenner": "banksy-di-faced-tenner",
  "banksy-dismaland": "banksy-dismaland",
  "banksy-girl-with-balloon": "banksy-girl-with-balloon",
  "banksy-walled-off-hotel": "banksy-walled-off-hotel",
  "damien-hirst-kate-moss": "damien-hirst-kate-moss",
  "damien-hirst-the-cure": "damien-hirst-the-cure",
  "damien-hirst-for-the-love-of-god": "damien-hirst-for-the-love-of-god",
  "damien-hirst-i-love-you": "damien-hirst-i-love-you",
  "damien-hirst-mickey-and-minnie-mouse":
    "damien-hirst-mickey-and-minnie-mouse",
  "damien-hirst-the-last-supper": "damien-hirst-the-last-supper",
  "damien-hirst-the-souls": "damien-hirst-the-souls",
  "damien-hirst-valium": "damien-hirst-valium",
  "damien-hirst-butterflies": "damien-hirst-butterflies",
  "damien-hirst-pills-and-medicine": "damien-hirst-pills-and-medicine",
  "damien-hirst-spin-paintings": "damien-hirst-spin-paintings",
  "damien-hirst-spots": "damien-hirst-spots",
  "david-hockney-celia": "david-hockney-celia",
  "david-hockney-pools": "david-hockney-pools",
  "david-hockney-a-bigger-book": "david-hockney-a-bigger-book",
  "david-hockney-ipad-drawings": "david-hockney-ipad-drawings",
  "david-shrigley-be-nice": "david-shrigley-be-nice",
  "david-shrigley-dont": "david-shrigley-dont",
  "david-shrigley-really-good": "david-shrigley-really-good",
  "david-shrigley-sell-your-soul": "david-shrigley-sell-your-soul",
  "david-shrigley-its-ok": "david-shrigley-its-ok",
  "ed-ruscha-angel": "ed-ruscha-angel",
  "ed-ruscha-news-mews-pews-brews-stews-dues":
    "ed-ruscha-news-mews-pews-brews-stews-and-dues",
  "ed-ruscha-sin": "ed-ruscha-sin",
  "ed-ruscha-hollywood": "ed-ruscha-hollywood",
  "ed-ruscha-mountain-prints": "ed-ruscha-mountain-prints",
  "ed-ruscha-standard-station": "ed-ruscha-standard-station",
  "harland-miller-happiness": "harland-miller-happiness",
  "harland-miller-too-cool-to-lose": "harland-miller-too-cool-to-lose",
  "harland-miller-penguin-prints": "harland-miller-penguin-prints",
  "harland-miller-who-cares-wins": "harland-miller-who-cares-wins",
  "invader-repetition-variation-evolution":
    "invader-repetition-variation-evolution",
  "invader-aladdin": "invader-aladdin",
  "invader-scooters": "invader-scooters",
  "invader-rubiks-cubes": "invader-rubiks-cubes",
  "katherine-bernhardt-save-the-amazon": "katherine-bernhardt-save-the-amazon",
  "katherine-bernhardt-merengue": "katherine-bernhardt-merengue",
  "katherine-bernhardt-et-phone-home": "katherine-bernhardt-et-phone-home",
  "katherine-bernhardt-pink-panther": "katherine-bernhardt-nike-panther",
  "kaws-halloween": "kaws-halloween",
  "kaws-bape": "kaws-bape",
  "kaws-blitz": "kaws-blitz",
  "kaws-along-the-way": "kaws-along-the-way",
  "kaws-cat-teeth-bank": "kaws-cat-teeth-bank",
  "kaws-clean-slate": "kaws-clean-slate",
  "kaws-lost-time": "kaws-lost-time",
  "kaws-passing-through": "kaws-passing-through",
  "kaws-resting-place": "kaws-resting-place",
  "kaws-share": "kaws-share",
  "kaws-small-lie": "kaws-small-lie",
  "kaws-together": "kaws-together",
  "kaws-tweety": "kaws-tweety",
  "kaws-undercover-bear": "kaws-undercover-bear",
  "kaws-gone": "kaws-gone",
  "kaws-bff": "kaws-bff",
  "kaws-four-foot-companion": "kaws-4-foot-companion",
  "kaws-alone-again": "kaws-alone-again",
  "kaws-astroboy": "kaws-astroboy",
  "kaws-chum": "kaws-chum",
  "kaws-dior": "kaws-dior",
  "kaws-dissected-and-flayed-companions":
    "kaws-dissected-and-flayed-companions",
  "kaws-holiday": "kaws-holiday",
  "kaws-kubrick": "kaws-kubrick",
  "kaws-mount-fuji": "kaws-mount-fuji",
  "kaws-no-ones-home": "kaws-no-ones-home",
  "kaws-pinocchio": "kaws-pinocchio",
  "kaws-seeing-watching": "kaws-seeing-slash-watching",
  "kaws-simpsons-kimpsons": "kaws-simpsons-kimpsons",
  "kaws-snoopy": "kaws-snoopy",
  "kaws-spongebob": "kaws-spongebob",
  "kaws-star-wars": "kaws-star-wars",
  "kaws-stay-steady": "kaws-stay-steady",
  "kaws-the-things-that-comfort": "kaws-the-things-that-comfort",
  "kaws-ups-and-downs": "kaws-ups-and-downs",
  "kaws-bearbrick": "kaws-bearbrick",
  "kaws-blame-game": "kaws-blame-game",
  "kaws-companions": "kaws-companions",
  "kaws-the-news": "kaws-the-news",
  "mr-brainwash-smile": "mr-brainwash-smile",
  "mr-brainwash-alfred-hitchcock": "mr-brainwash-alfred-hitchcock",
  "mr-brainwash-batman": "mr-brainwash-batman",
  "mr-brainwash-beatles": "mr-brainwash-beatles",
  "mr-brainwash-charlie-chaplin": "mr-brainwash-charlie-chaplin",
  "mr-brainwash-david-bowie": "mr-brainwash-david-bowie",
  "mr-brainwash-elvis-presley": "mr-brainwash-elvis-presley",
  "mr-brainwash-follow-your-dreams": "mr-brainwash-follow-your-dreams",
  "mr-brainwash-jimi-hendrix": "mr-brainwash-jimi-hendrix",
  "mr-brainwash-juxtapose": "mr-brainwash-juxtapose",
  "mr-brainwash-kate-moss": "mr-brainwash-kate-moss",
  "mr-brainwash-madonna": "mr-brainwash-madonna",
  "mr-brainwash-marilyn-monroe": "mr-brainwash-marilyn-monroe",
  "mr-brainwash-spiderman": "mr-brainwash-spiderman",
  "mr-brainwash-work-well-together": "mr-brainwash-work-well-together",
  "mr-brainwash-albert-einstein": "mr-brainwash-albert-einstein",
  "mr-brainwash-life-is-beautiful": "mr-brainwash-life-is-beautiful",
  "mr-brainwash-minnie-and-mickey-mouse":
    "mr-brainwash-minnie-and-mickey-mouse",
  "mr-brainwash-spray-cans": "mr-brainwash-spray-cans",
  "roy-lichtenstein-crak": "roy-lichtenstein-crak",
  "roy-lichtenstein-drowning-girl": "roy-lichtenstein-drowning-girl",
  "roy-lichtenstein-mickey-mouse": "roy-lichtenstein-mickey-mouse",
  "roy-lichtenstein-reverie": "roy-lichtenstein-reverie",
  "roy-lichtenstein-sandwich-and-soda": "roy-lichtenstein-sandwich-and-soda",
  "roy-lichtenstein-sweet-dreams-baby": "roy-lichtenstein-sweet-dreams-baby",
  "roy-lichtenstein-this-must-be-the-place":
    "roy-lichtenstein-this-must-be-the-place",
  "roy-lichtenstein-as-i-opened-fire": "roy-lichtenstein-as-i-opened-fire",
  "roy-lichtenstein-chinese-landscapes": "roy-lichtenstein-chinese-landscapes",
  "roy-lichtenstein-cow-going-abstract-art":
    "roy-lichtenstein-cow-going-abstract-art",
  "roy-lichtenstein-mirrors": "roy-lichtenstein-mirrors",
  "roy-lichtenstein-moonscapes": "roy-lichtenstein-moonscapes",
  "roy-lichtenstein-music": "roy-lichtenstein-music",
  "roy-lichtenstein-pyramids": "roy-lichtenstein-pyramids",
  "roy-lichtenstein-spray-cans": "roy-lichtenstein-spray-cans",
  "roy-lichtenstein-sunrises": "roy-lichtenstein-sunrises",
  "roy-lichtenstein-the-surrealist-series":
    "roy-lichtenstein-the-surrealist-series",
  "roy-lichtenstein-water-lilies": "roy-lichtenstein-water-lilies",
  "roy-lichtenstein-whaam": "roy-lichtenstein-whaam",
  "roy-lichtenstein-expressionist-woodcuts":
    "roy-lichtenstein-expressionist-woodcuts",
  "roy-lichtenstein-brushstrokes": "roy-lichtenstein-brushstrokes",
  "roy-lichtenstein-crying-girl": "roy-lichtenstein-crying-girl",
  "roy-lichtenstein-impressionism": "roy-lichtenstein-impressionism",
  "sterling-ruby-ashtrays": "sterling-ruby-ashtrays",
  "stik-dancers": "stik-dancers",
  "stik-sleeping-babies": "stik-sleeping-babies",
  "stik-liberty": "stik-liberty",
  "stik-walk": "stik-walk",
  "takashi-murakami-727": "takashi-murakami-727",
  "takashi-murakami-chaos": "takashi-murakami-chaos",
  "takashi-murakami-daruma": "takashi-murakami-daruma",
  "takashi-murakami-doraemon": "takashi-murakami-doraemon",
  "takashi-murakami-homage-to-francis-bacon":
    "takashi-murakami-homage-to-francis-bacon",
  "takashi-murakami-tan-tan-bo": "takashi-murakami-tan-tan-bo",
  "takashi-murakami-time-bokan": "takashi-murakami-time-bokan",
  "takashi-murakami-flower-balls": "takashi-murakami-flower-balls",
  "takashi-murakami-enso": "takashi-murakami-enso",
  "takashi-murakami-jellyfish-eyes": "takashi-murakami-jellyfish-eyes",
  "takashi-murakami-mr-dob": "takashi-murakami-mr-dob",
}
