---
apiVersion: v1
kind: Namespace
metadata:
  name: '3803'
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: force-web
  namespace: '3803'
spec:
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: force
        component: web
        layer: application
      name: force-web
      namespace: default
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: tier
                operator: In
                values:
                - foreground
      containers:
      - env:
        - name: DD_TRACE_AGENT_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        envFrom:
        - configMapRef:
            name: force-environment
        image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/force:3803
        imagePullPolicy: Always
        name: force-web
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            httpHeaders:
            - name: X-FORWARDED-PROTO
              value: https
            path: /system/up
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            memory: 1.5Gi
          requests:
            cpu: 700m
            memory: 1Gi
      - env:
        - name: NGINX_DEFAULT_CONF
          valueFrom:
            configMapKeyRef:
              key: force
              name: nginx-config
        image: artsy/docker-nginx:latest
        lifecycle:
          preStop:
            exec:
              command:
              - /usr/sbin/nginx
              - -s
              - quit
        name: force-nginx
        ports:
        - containerPort: 8080
      dnsConfig:
        options:
        - name: ndots
          value: '1'
      dnsPolicy: ClusterFirst
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: force-web
  namespace: '3803'
spec:
  maxReplicas: 3
  minReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: force-web
  targetCPUUtilizationPercentage: 70
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-access-log-emit-interval: '60'
    service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: 'true'
    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-name: artsy-elb-logs
    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-prefix: staging-force
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: 'true'
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '300'
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:iam::585031190124:server-certificate/2018-01-17_artsy-net-wildcard
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: '443'
  labels:
    app: force
    component: web
    layer: application
  name: force-web
  namespace: '3803'
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app: force
    component: web
    layer: application
  sessionAffinity: None
  type: LoadBalancer
