---
version: "3.8"
services:
  force:
    image: hokusai_force:latest
    build:
      context: ../
      target: builder-src
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://force-redis:6379/0
      - OPENREDIS_URL=redis://force-redis:6379/0
      - PORT=5000
    env_file:
      - ../.env.shared
      - ../.env
    command: ["yarn", "start:dev"]
    ports:
      - 5000:5000
    volumes:
      - ../:/app
      # prevents bind mount from overwriting node_modules in docker image.
      - /app/node_modules
    depends_on:
      - force-redis
  force-redis:
    image: redis:3.2-alpine
    ports:
      - 6379:6379
