---
version: "3.8"
services:
  force:
    build:
      context: ../
      dockerfile: dev.Dockerfile
    env_file:
      - ../.env.shared
      - ../.env.development
      - ../.env
    command: ["yarn", "start"]
    ports:
      - 4000:4000
    volumes:
      - ../:/app
      # prevents bind mount from overwriting node_modules in docker image.
      - /app/node_modules
