apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: force-web
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: force
        layer: application
        component: web
      name: force-web
      namespace: default
    spec:
      containers:
        - name: force-web
          env:
            - name: DD_TRACE_AGENT_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          envFrom:
            - configMapRef:
                name: force-environment
          image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/force:production
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              port: 5000
              path: /system/up
              httpHeaders:
                - name: X-FORWARDED-PROTO
                  value: https
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 700m
              memory: 1Gi
            limits:
              memory: 1.5Gi
      dnsPolicy: Default
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: tier
                    operator: In
                    values:
                      - foreground

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: force
    layer: application
    component: web
  name: force-web
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: 'arn:aws:iam::585031190124:server-certificate/2018-01-17_artsy-net-wildcard'
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: 'http'
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: '443'
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: 'true'
    service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '300'
spec:
  ports:
    - port: 443
      protocol: TCP
      name: https
      targetPort: 5000
    - port: 80
      protocol: TCP
      name: http
      targetPort: 5000
  selector:
    app: force
    layer: application
    component: web
  sessionAffinity: None
  type: LoadBalancer
