apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: force-web
spec:
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: force
        layer: application
        component: web
      name: force-web
      namespace: default
    spec:
      containers:
        - name: force-web
          env:
            - name: PORT
              value: "5000"
            - name: DD_TRACE_AGENT_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          envFrom:
            - configMapRef:
                name: force-environment
          image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/force:production
          imagePullPolicy: Always
          ports:
            - name: force-http
              containerPort: 5000
          readinessProbe:
            httpGet:
              port: force-http
              path: /system/up
              httpHeaders:
                - name: X-FORWARDED-PROTO
                  value: https
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 10
          resources:
            requests:
              cpu: 1000m
              memory: 1536Mi
            limits:
              memory: 3.5Gi
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
      dnsPolicy: ClusterFirst
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: tier
                    operator: In
                    values:
                      - foreground
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: force-web
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: force-web
  minReplicas: 3
  maxReplicas: 20
  targetCPUUtilizationPercentage: 70
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: force
    component: web
    layer: application
  name: force-web-internal
  namespace: default
spec:
  ports:
    - port: 5000
      protocol: TCP
      name: force-http
      targetPort: force-http
  selector:
    app: force
    layer: application
    component: web
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: force
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: "{{ cloudflareIpSourceRanges|join(',') }}"
spec:
  rules:
    - host: www.artsy.net
      http:
        paths:
          - path: /
            backend:
              serviceName: force-web-internal
              servicePort: force-http
