apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: force
    layer: application
    component: web
    app.kubernetes.io/version: production
  name: force-web
spec:
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: force
      layer: application
      component: web
  template:
    metadata:
      labels:
        app: force
        layer: application
        component: web
        app.kubernetes.io/version: production
      name: force-web
      namespace: default
    spec:
      containers:
      - name: force-web
        env:
        - name: PORT
          value: '5000'
        - name: DD_TRACE_AGENT_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: DD_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/version']
        envFrom:
        - configMapRef:
            name: force-environment
        image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/force:production
        imagePullPolicy: Always
        ports:
        - name: force-http
          containerPort: 5000
        readinessProbe:
          httpGet:
            port: force-http
            path: /system/up
            httpHeaders:
            - name: X-FORWARDED-PROTO
              value: https
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 10
        resources:
          requests:
            cpu: 1000m
            memory: 1536Mi
          limits:
            memory: 3.5Gi
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - sleep 10
      dnsPolicy: ClusterFirst
      dnsConfig:
        options:
        - name: ndots
          value: '1'
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: tier
                operator: In
                values:
                - foreground
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: force-web
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: force-web
  minReplicas: 3
  maxReplicas: 20
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 1800
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 70
        type: Utilization
    type: Resource
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: force
    component: web
    layer: application
  name: force-web-internal
  namespace: default
spec:
  ports:
  - port: 5000
    protocol: TCP
    name: force-http
    targetPort: force-http
  selector:
    app: force
    layer: application
    component: web
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: force
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ cloudflareIpSourceRanges|join(',') }}
spec:
  ingressClassName: nginx
  rules:
  - host: www.artsy.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: force-web-internal
          servicePort: force-http
