---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: force-web
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: force
        layer: application
        component: web
      name: force-web
      namespace: default
    spec:
      containers:
        - name: force-web
          envFrom:
          - configMapRef:
              name: force-environment
          image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/force:staging
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: force
    layer: application
    component: web
  name: force-web
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:iam::585031190124:server-certificate/2016-01-19_artsy-net-wildcard"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
spec:
  ports:
  - port: 443
    protocol: TCP
    name: https
    targetPort: 80
  selector:
    app: force
    layer: application
    component: web
  sessionAffinity: None
  type: LoadBalancer
