import compact from "lodash/compact"
interface Item {
  label: string
  value: string
  [key: string]: string | number | boolean
}

export function getArtworkLocationSearchableText(item: Item) {
  const parts = item.label.split(", ")
  const country = parts[parts.length - 1]
  const texts = compact([item.label, SYNONYM_MAP[country], REGION_MAP[country]])
  return texts.join("; ")
}

const SYNONYM_MAP = {
  USA: "United States of America; U.S.A.",
  "United Kingdom": "Great Britain; UK; U.K.",
  "Côte d'Ivoire": "Ivory Coast",
  Turkey: "Türkiye; Turkiye",
  Türkiye: "Turkey; Turkiye",
  "Czech Republic": "Czechia",
  Czechia: "Czech Republic",
  Swaziland: "Eswatini",
}

const REGION_MAP = {
  Albania: "Europe",
  Algeria: "Africa",
  Andorra: "Europe",
  Angola: "Africa",
  Argentina: "South America; Latin America",
  Armenia: "West Asia; Middle East",
  Australia: "Oceania",
  Austria: "Europe",
  Azerbaijan: "West Asia; Middle East",
  Bahrain: "West Asia; Middle East",
  Bangladesh: "South Asia",
  Barbados: "Caribbean; Latin America",
  Belarus: "Europe; Eastern Europe",
  Belgium: "Europe",
  Benin: "Africa",
  Bermuda: "North America; Caribbean",
  Bolivia: "South America; Latin America",
  "Bosnia and Herzegovina": "Europe",
  Botswana: "Africa",
  Brazil: "South America; Latin America",
  Bulgaria: "Europe; Eastern Europe",
  Burma: "Southeast Asia",
  Cambodia: "Southeast Asia",
  Cameroon: "Africa",
  Canada: "North America",
  "Cayman Islands": "Caribbean",
  Chile: "South America; Latin America",
  China: "East Asia",
  Colombia: "South America; Caribbean; Latin America",
  "Cook Islands": "Oceania",
  "Costa Rica": "Central America; Caribbean; Latin America",
  "Côte d'Ivoire": "Africa",
  Croatia: "Europe",
  Cuba: "Caribbean; Latin America",
  Curaçao: "Caribbean",
  Cyprus: "Europe; Middle East",
  "Czech Republic": "Europe; Eastern Europe",
  Czechia: "Europe; Eastern Europe",
  "Democratic Republic of the Congo": "Africa",
  Denmark: "Europe; Scandinavia",
  "Dominican Republic": "Caribbean; Latin America",
  Ecuador: "South America; Latin America",
  Egypt: "Africa; Middle East",
  "El Salvador": "Central America; Latin America",
  Estonia: "Europe",
  Ethiopia: "Africa",
  Finland: "Europe",
  France: "Europe",
  Gaza: "West Asia; Middle East",
  Georgia: "West Asia; Middle East",
  Germany: "Europe",
  Ghana: "Africa",
  Greece: "Europe",
  Grenada: "Caribbean; Latin America",
  Guadeloupe: "Caribbean; Latin America",
  Guatemala: "Central America; Caribbean; Latin America",
  Guyana: "South America; Caribbean; Latin America",
  Haiti: "Caribbean; Latin America",
  "Hong Kong": "East Asia",
  Hungary: "Europe; Eastern Europe",
  Iceland: "Europe",
  India: "South Asia",
  Indonesia: "Southeast Asia",
  Iran: "West Asia; Middle East",
  Iraq: "West Asia; Middle East",
  Ireland: "Europe",
  Israel: "West Asia; Middle East",
  Italy: "Europe",
  Jamaica: "Caribbean; Latin America",
  Japan: "East Asia",
  Jersey: "Europe",
  Jordan: "West Asia; Middle East",
  Kazakhstan: "Central Asia",
  Kenya: "Africa",
  Kuwait: "West Asia; Middle East",
  Latvia: "Europe",
  Lebanon: "West Asia; Middle East",
  Liechtenstein: "Europe",
  Lithuania: "Europe",
  Luxembourg: "Europe",
  Madagascar: "Africa",
  Malaysia: "Southeast Asia",
  Malta: "Europe",
  Martinique: "Caribbean; Latin America",
  Mauritius: "Africa",
  Mexico: "North America; Latin America",
  Moldova: "Europe; Eastern Europe",
  Monaco: "Europe",
  Mongolia: "East Asia",
  Montenegro: "Europe",
  Morocco: "Africa; Middle East",
  Mozambique: "Africa",
  Myanmar: "Southeast Asia",
  "Myanmar (Burma)": "Southeast Asia",
  Namibia: "Africa",
  Nepal: "South Asia",
  Netherlands: "Europe",
  "New Zealand": "Oceania",
  Nicaragua: "Central America; Caribbean; Latin America",
  Nigeria: "Africa",
  "North Macedonia": "Europe",
  Norway: "Europe; Scandinavia",
  Pakistan: "South Asia",
  Panama: "Central America; Caribbean; Latin America",
  Paraguay: "South America; Latin America",
  Peru: "South America; Latin America",
  Philippines: "Southeast Asia",
  Poland: "Europe; Eastern Europe",
  Portugal: "Europe",
  "Puerto Rico": "Caribbean; Latin America",
  Qatar: "West Asia; Middle East",
  Réunion: "Africa",
  Romania: "Europe; Eastern Europe",
  Russia: "Eastern Europe",
  Rwanda: "Africa",
  "Saint Barthélemy": "Caribbean; Latin America",
  "San Marino": "Europe",
  "Saudi Arabia": "West Asia; Middle East",
  Senegal: "Africa",
  Serbia: "Europe",
  Seychelles: "Africa",
  Singapore: "Southeast Asia",
  Slovakia: "Europe; Eastern Europe",
  Slovenia: "Europe",
  "South Africa": "Africa",
  "South Korea": "East Asia",
  Spain: "Europe",
  "Sri Lanka": "South Asia",
  Suriname: "South America; Caribbean; Latin America",
  Swaziland: "Africa",
  Sweden: "Europe; Scandinavia",
  Switzerland: "Europe",
  Taiwan: "East Asia",
  Thailand: "Southeast Asia",
  "The Bahamas": "Caribbean; Latin America",
  "Trinidad and Tobago": "Caribbean; Latin America",
  Tunisia: "Africa; Middle East",
  Turkey: "Europe; Middle East",
  Türkiye: "Europe; Middle East",
  Turkmenistan: "Central Asia",
  "U.S. Virgin Islands": "Caribbean",
  Uganda: "Africa",
  Ukraine: "Europe; Eastern Europe",
  "United Arab Emirates": "West Asia; Middle East",
  "United Kingdom": "Europe",
  Uruguay: "South America; Latin America",
  USA: "North America",
  Uzbekistan: "Central Asia",
  Venezuela: "South America; Caribbean; Latin America",
  Vietnam: "Southeast Asia",
  Zambia: "Africa",
  Zimbabwe: "Africa",
}
