UserEditFormView = require '../user_edit/view.coffee'
template = -> require('./template.pug') arguments...

module.exports = class AdvancedCollectorSettingsFormView extends UserEditFormView
  template: -> template arguments...
