export const DESKTOP_NAV_BAR_TOP_TIER_HEIGHT = 60
export const DESKTOP_NAV_BAR_BOTTOM_TIER_HEIGHT = 44
export const MOBILE_NAV_AUTHENTICATION_HEIGHT = 50
export const NAV_BAR_HEIGHT =
  DESKTOP_NAV_BAR_TOP_TIER_HEIGHT + DESKTOP_NAV_BAR_BOTTOM_TIER_HEIGHT
export const MOBILE_LOGGED_IN_NAV_HEIGHT = DESKTOP_NAV_BAR_TOP_TIER_HEIGHT
export const MOBILE_NAV_HEIGHT =
  DESKTOP_NAV_BAR_TOP_TIER_HEIGHT + MOBILE_NAV_AUTHENTICATION_HEIGHT
