import { MyCollectionRoutePaginationContainer } from "Apps/Settings/Routes/MyCollection/MyCollectionRoute"

export const CollectorProfileMyCollectionRoutePaginationContainer = MyCollectionRoutePaginationContainer
