export { CheckoutMutationError } from "Apps/Order/Components/ExpressCheckout/Util/mutationHandling"

/**
 * Error codes raised by Exchange (gravity) and surfaced through metaphysics as
 * `OrderMutationError.mutationError.code`. Use these constants instead of bare
 * string literals when branching on `error.code` so renames are caught by
 * TypeScript.
 */
const ExchangeErrorCodes = {
  MISSING_REGION: "missing_region",
  MISSING_COUNTRY: "missing_country",
  MISSING_POSTAL_CODE: "missing_postal_code",
  DESTINATION_COULD_NOT_BE_GEOCODED: "destination_could_not_be_geocoded",
} as const

type ExchangeErrorCode =
  (typeof ExchangeErrorCodes)[keyof typeof ExchangeErrorCodes]

/**
 * Error codes generated by Force itself (not Exchange). Used when client-side
 * validation needs to surface a code-keyed failure to the same handlers that
 * consume server errors.
 */
const LocalErrorCodes = {
  NO_SHIPPING_OPTIONS: "no_shipping_options",
} as const
type LocalErrorCode = (typeof LocalErrorCodes)[keyof typeof LocalErrorCodes]

export class LocalCheckoutError extends Error {
  code: LocalErrorCode

  constructor(code: LocalErrorCode, message?: string) {
    super(message)
    this.code = code
    this.name = "LocalCheckoutError"
  }
}

export type KnownErrorCodes = LocalErrorCode | ExchangeErrorCode
