name: ☢️ Yarn
on:
  pull_request:
    types: [opened, synchronize, edited, review_requested, review_request_removed, labeled, unlabeled, milestoned, demilestoned]

jobs:
  danger-yarn:
    uses: artsy/duchamp/.github/workflows/run-yarn.yml@test-danger-token
    secrets:
      DANGER_TOKEN: ${{ secrets.DANGER_TOKEN }}